.travis.yml

Rackspace deploy broken from OSX - use workaround.

BF: workaround Rackspace deploy bug

---

README.rst

Removed trailing space

---

.gitmodules
.travis.yml
config.sh
osx_build_deps.sh

Refactoring using `multibuild` submodule to run and test builds of manylinux1 wheels.
Builds and tests on 64- and 32-bit.

MRG: refactored repo to build manylinux1 wheels

---

README.rst

Please could someone who has permissions also update this bit on https://github.com/python-pillow/pillow-wheels:

README: Not only OS X wheel builder

---

.travis.yml

Updated multibuild, updated travis osx_image to 9.2

---

.travis.yml

Fixes https://github.com/python-pillow/Pillow/issues/3068.

Build on Xcode 6.4

---

config.sh

Makes use of https://github.com/matthew-brett/multibuild/pull/56

Simplified custom freetype build

---

README.rst

Companion to https://github.com/python-pillow/Pillow/pull/3320

Improved shell commands

---

.travis.yml

For https://github.com/python-pillow/Pillow/issues/3581.

Drop support for EOL Python 3.4

---

README.rst
update-pillow-tag.sh

Similar to https://github.com/python-pillow/docker-images/pull/50.
And fix some typos.
Once merged, can update https://github.com/python-pillow/Pillow/blob/master/RELEASING.md#mac-and-linux

Add script to update Pillow

---

config.sh

367 was fixed as part of OpenJpeg 2.1.1 - https://github.com/uclouvain/openjpeg/blob/v2.1.1/CHANGELOG.md

Removed custom macOS openjpeg command

---

.travis.yml

Equivalent of https://github.com/python-pillow/docker-images/pull/66

Also test latest Pillow

---

README.rst

Companion to https://github.com/python-pillow/Pillow/pull/4106

Do not download dev wheels

---

config.sh

Changed comments to refer to "OS X"

---

.travis.yml

Just trying to break #147 down into more manageable chunks, here are PyPy jobs for Linux

Added Linux PyPy

---

.travis.yml
config.sh

Adds macOS PyPy jobs to help https://github.com/python-pillow/Pillow/issues/4655
Also installs NumPy with OpenBLAS, as per https://github.com/python-pillow/Pillow/pull/4711

Added macOS PyPy

---

README.rst

Updated PyPI instructions

---

.github/mergify.yml

For https://github.com/python-pillow/Pillow/issues/4900. 
Like https://github.com/python-pillow/docker-images/pull/84 and https://github.com/python-pillow/docker-images/pull/86.

Add Mergify config

---

.github/mergify.yml
README.rst

For https://github.com/python-pillow/Pillow/issues/5020.

Update for travis-ci.com

---

.github/workflows/build.sh
config.sh

Like https://github.com/python-pillow/Pillow/pull/4465

Invoke pip using python3

---

update-pillow-tag.sh

Equivalent of https://github.com/python-pillow/docker-images/pull/107

Combined git submodule commands

---

.github/workflows/build.sh

After the merging of https://github.com/matthew-brett/multibuild/pull/374

multibuild now includes PyPy 7.3.3

---

config.sh

For https://github.com/python-pillow/pillow-wheels/issues/198#issuecomment-837322738

Fix expected features list on Travis

---

.github/workflows/wheels.yml
config.sh

Helps https://github.com/python-pillow/Pillow/issues/5569
multibuild is updated to include https://github.com/matthew-brett/multibuild/pull/422

Added Python 3.10 macOS jobs

---

config.sh

Upgraded numpy on 32-bit PyPy3.7 to match 64-bit

---

README.rst

Updated README for new API key location

---

.github/workflows/wheels.yml
.travis.yml
README.rst
config.sh
update-pillow-tag.sh

For https://github.com/python-pillow/Pillow/issues/5671.

Rename master to main

---

config.sh

Updating multibuild to include https://github.com/multi-build/multibuild/pull/454

multibuild now includes build_libjpeg_turbo

---

.editorconfig

Applying https://github.com/python-pillow/Pillow/commit/d32d96fab1ff7463baee28990cafb426b15568ca to this repository

Remove redundant property already defined in another section

---

config.sh

Updated zlib to 1.2.13

---

.github/workflows/lint.yml
.github/workflows/wheels.yml

Similar to https://github.com/python-pillow/Pillow/pull/6621.

Add concurrency so old workflows are cancelled in favour of new ones

---

config.sh

libXau 1.0.11 has been released - https://www.x.org/pub/individual/lib

Updated libXau to 1.0.11

---

dependency_licenses/FREETYPE2.txt
dependency_licenses/HARFBUZZ.txt
dependency_licenses/LIBPNG.txt

Updated licenses with newer versions from the dependencies.

Updated licenses

---

.github/workflows/build.sh
.github/workflows/wheels-linux.yml
config.sh

https://github.com/python-pillow/Pillow/issues/6941#issuecomment-1604058002
> I suggest we drop all the 32-bit wheels and testing.

Removed 32-bit wheels

---

config.sh

freetype 2.13.1 has been released - https://freetype.org/

Updated freetype to 2.13.1

---

config.sh

brotli 1.1.0 has been released - https://github.com/google/brotli/releases/tag/v1.1.0

Updated brotli to 1.1.0

---

config.sh

Resolves https://github.com/python-pillow/Pillow/issues/6554

Fixed brotli detection on aarch64
