python-pillow/pillow-wheels

.travis.yml
Merging into a new "latest" branch.
The last build on a branch called "latest" at the python-pillow/pillow-wheels repo will be restarted after successful builds on the master branch at python-pillow/Pillow.
The Rackspace provider won't take deploys from non-master branches, but the `on: condition:` is an extra safeguard to prevent `LATEST_TAG` builds attempting to deploy. The condition can also go into master with `LATEST_TAG` commented out.
See also PR https://github.com/python-pillow/Pillow/pull/1067 and issue https://github.com/python-pillow/Pillow/issues/1065
=> Run OS X tests after successful Linux build

.travis.yml
Update to latest terryfy, that has different wording for the
'latest-tag'.  Re-enable build of latest tag by default.
=> Update to latest terrfy; enable build latest tag

.travis.yml
I believe the 'latest' branch was in fact building the last tag rather the
latest commit, which I think was the intention.
=> MRG: fix building of latest OSX commit

.travis.yml
Python 3.5 build need the latest version of wheel installed into the
virtualenv.  I believe the copy of wheel that virtualenv gets depends on your
virtualenv version, not the version of wheel you have installed when you create
the virtualenv.
Also, remove workaround for fixed Rackspace deploy bug on travis-ci.
=> MRG: fix Python 3.5 building; remove workaround

.travis.yml
XCode image causing odd bug in bash scripting in OSX:
https://github.com/python-pillow/pillow-wheels/issues/45
=> BF: work round Xcode OSX image change

.travis.yml
Travis has changed their open source OSX builds to only do 2 at a time. So, to speed up the overall flow, we're spacing these out so that we will generally run 2 OSX + 3 linux builds at a time. 
(note that linux builds are faster, so there's likely to be some overlap.)
=> Rearrange OSX builds due to 2 at a time limit

config.sh
This setting has been the same since #40, a year ago.
=> Removed setting of Linux-specific Freetype version

.travis.yml
* Update multibuild to latest master, which now includes the newly released Python 3.7.0 final (https://github.com/matthew-brett/multibuild/commit/7cca00d3d1d590a3ed34185ef1db1cd970c3a3a1)
* Add Python 3.7 to the Travis builds (from @jaraco's https://github.com/python-pillow/pillow-wheels/pull/86)
=> Add Python 3.7

README.rst
This matches https://github.com/python-pillow/Pillow/blob/master/RELEASING.md#mac-and-linux better, including https://github.com/python-pillow/Pillow/pull/3321. Also, the `-a` git flags adds all modified files. This just adds Pillow instead.
=> Changed shell commands to better match main repository

.travis.yml, config.sh
Here's a rebuild of master, which now fails:
* https://travis-ci.org/python-pillow/pillow-wheels/builds/435068720
See:
* https://github.com/matthew-brett/multibuild/issues/202
* https://github.com/pypa/wheel/issues/255
=> Pin wheel to 0.31.1 to work around API break in 0.32.0

config.sh
I have found new errors generated on Linux by the upgrade to wheel 0.32, so this is a sequel to #100.
https://travis-ci.org/python-pillow/pillow-wheels/jobs/435427307#L4860
```
Traceback (most recent call last):
File "/usr/local/bin/auditwheel", line 11, in <module>
sys.exit(main())
File "/opt/_internal/cpython-3.6.6/lib/python3.6/site-packages/auditwheel/main.py", line 49, in main
rval = args.func(args, p)
File "/opt/_internal/cpython-3.6.6/lib/python3.6/site-packages/auditwheel/main_repair.py", line 43, in execute
from .repair import repair_wheel
File "/opt/_internal/cpython-3.6.6/lib/python3.6/site-packages/auditwheel/repair.py", line 13, in <module>
from .wheeltools import InWheelCtx, add_platforms
File "/opt/_internal/cpython-3.6.6/lib/python3.6/site-packages/auditwheel/wheeltools.py" …
```
=> Resolved auditwheel error by further pinning of wheel to 0.31.1

config.sh
manylinux has reverted wheel back to 0.31.1 - https://github.com/pypa/manylinux/pull/229 - so this PR reverts the workaround for that
While this PR removes code that is now unnecessary, I also understand if you wish to ignore this because wheel 0.32 is still causing other issues
=> Revert "Resolved auditwheel error by further pinning of wheel to 0.31.1"

.travis.yml
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
=> 'sudo: required' no longer required

.travis.yml, config.sh
Resolves #96. Alternative to #97
`build_giflib` is the only dependency from https://github.com/matthew-brett/multibuild/blob/6713093b24c014168d282df1111ed6cdc141da55/library_builders.sh#L198 that is not already built.
On current master, the libwebp build reports '[checking whether clang supports -msse4.1... no](https://travis-ci.org/python-pillow/pillow-wheels/jobs/440600001#L3737)'. When updating `osx_image`, errors related to sse4.1 then appear. #97 solves this by disabling sse4.1. The flags change in this PR causes the libwebp build to report '[checking whether clang supports -msse4.1... yes](https://travis-ci.org/python-pillow/pillow-wheels/jobs/440973130#L3696)', and then continue without error when `osx_image` is updated.
=> Updated travis osx_image to 9.4

.travis.yml
https://github.com/python-pillow/Pillow/pull/3087 removed test_scipy.py, meaning that scipy is no longer used in the tests.
=> Removed scipy as test dependency

config.sh
Resolves https://github.com/python-pillow/Pillow/issues/3441
Here are speed comparisons between the different Pillow versions installed from pip, a local wheel file of 6.0.0 (the only differences between this and pip 6.0.0 should be Freetype, as these wheels were created on TravisCI), and a local wheel with this PR.
Pillow | 2.7 | 3.7
-- | -- | --
5.0.0 | 2.01 | 1.71
5.1.0 | 4.3  | 1.59
5.2.0 | 4.3  | 4.63
5.3.0 | 4.3  | 4.61
5.4.0 | 4.38 | 4.56
5.4.1 | 4.37 | 4.58
6.0.0 | 4.36 | 4.61
6.0.0 Local | 4.38 | 4.64
6.0.0 Local With CFLAGS fix | 2.11 | 2.22
=> Include both multibuild and jpeg default CFLAGS

config.sh
Resolves https://github.com/python-pillow/Pillow/issues/4040. libwebp equivalent of #117
Takes the new CFLAGs from https://github.com/webmproject/libwebp/blob/0e48d889eb90363c6ebf8ea276bae4d892f9d3c0/makefile.unix#L112
Testing with the following code -
```python
from PIL import Image
import time
im = Image.open('hopper.jpg')
start = time.time()
for i in range(0, 1000):
im.save('out.webp')
print(time.time() - start)
```
Speed | macOS | Linux
-- | -- | --
[Timer script](https://github.com/radarhere/pillow-wheels/commit/fdd4d15c6bd68f7d9f34b2e16964846224ce6852) | [19.58s](https://travis-ci.org/radarhere/pillow-wheels/jobs/579776646#L4212) | [22.19s](https://travis-ci.org/radarhere/pillow-wheels/jobs/579776647#L4971)
[Fix](https://github.com/radarhere/pillow-wheels/commit/2199bcecbc57c8236501c …
=> Include both multibuild and libwebp default CFLAGS

.travis.yml
https://github.com/python-pillow/pillow-wheels/blob/9e7dcea7395b4b30fc78da7b197c20ed380a0130/.travis.yml#L223-L224
`clean_code` actually already updates - https://github.com/matthew-brett/multibuild/blob/160edd796c25c0aa400b73ce79cecfa1758c181e/common_utils.sh#L211
So changing `BUILD_COMMIT` is an alternative to using the submodule command - and it avoids the merge conflicts that are causing pillow-wheels to fail at the moment, [caused by 6.2.1.](https://github.com/python-pillow/Pillow/issues/4152#issuecomment-544647530)
=> Fixed updating to latest from non-master branch

.travis.yml
See https://github.com/python-pillow/Pillow/issues/3642
=> Removed Python 2 jobs

.travis.yml
Moves multibuild back in line with master.
Stops specifying ``MB_PYTHON_OSX_VER``, added in #127, now that the updated multibuild has good defaults for this - https://github.com/matthew-brett/multibuild/pull/275
=> Updated multibuild

config.sh
Helps https://github.com/python-pillow/Pillow/issues/4234
The [default bzip2 version is 1.0.6](https://github.com/matthew-brett/multibuild/blob/88a0b6f0eb770cf9f95792d66410e7696ce3d384/library_builders.sh#L16). This PR updates that to 1.0.8. macOS is avoided for now due to a compilation error.
I'm using custom code instead of `build_bzip2` because the URL in the multibuild code does not have access to the 1.0.8 version - see https://github.com/matthew-brett/multibuild/pull/282 for my PR to fix that
=> Updated bzip2 to 1.0.8 for Linux

.travis.yml
Resolves #133
For whatever reason, fixes the failing Python 3.8 macOS tests in master.
=> Changed Travis osx_image to 9.3

config.sh
Since #138 updated multibuild, https://github.com/matthew-brett/multibuild/pull/282 is now included. This updates the bzip2 download URL to allow for bzip2 versions other than 1.0.6.
As noted in #131, the absence of this required custom code. Now, the custom code introduced by #131 can be removed, with multibuild's [`build_freetype`](https://github.com/matthew-brett/multibuild/blob/6b0ddb5281f59d976c8026c082c9d73faf274790/library_builders.sh#L206-L208) automatically running [`build_bzip2`](https://github.com/matthew-brett/multibuild/blob/6b0ddb5281f59d976c8026c082c9d73faf274790/library_builders.sh#L138-L146)
=> Removed customisation of bzip2 build

config.sh
Helps https://github.com/python-pillow/Pillow/issues/4558
=> Compile libxcb on macOS

config.sh
https://github.com/python-pillow/Pillow/issues/4558#issuecomment-614308890 points out that in pillow-wheels, after tests are run, we are currently [testing for the expected codes and modules, but not features](https://github.com/python-pillow/pillow-wheels/blob/3946cb73a9a6cd91f105f4070c4a5f3945572905/config.sh#L81-L94). This PR adds checking for expected features.
=> Test features

config.sh
Resolves https://github.com/python-pillow/Pillow/issues/4558
Trying to compile libxcb on Linux, I encountered
```
configure: error: Package requirements (xcb-proto >= 1.14) were not met:
Variable 'pc_sysrootdir' not defined in '/usr/local/lib/pkgconfig/xcb-proto.pc'
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
Alternatively, you may set the environment variables XCBPROTO_CFLAGS
and XCBPROTO_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
Printing `/usr/local/lib/pkgconfig/xcb-proto.pc`, I found
```
prefix=/usr/local
exec_prefix=${prefix}
datarootdir=${prefix}/share
datadir=${datarootdir}
libdir=${exec_prefix}/lib
xcbincludedir=${pc_sysrootdir}${datadir}/xcb …
```
=> Compile libxcb on Linux

.travis.yml, config.sh
- update multibuild to latest devel commit
- add wheels for PyPy3 on linux64, aarch64 for python 3.6, 3.7, 3.8
When will Pillow drop support for python 3.5?
=> Add aarch64 wheels

.travis.yml
Re: https://github.com/python-pillow/Pillow/pull/4746
Before merging, we can wait until the 7.2.x release (https://github.com/python-pillow/Pillow/issues/4658) is in the clear and not needing any point releases.
=> Drop Python 3.5

.travis.yml
Fixes https://github.com/python-pillow/pillow-wheels/issues/146, using one of @mattip's suggestions.
Based on Cython's config:
* https://github.com/MacPython/cython-wheels/blob/b421040fd59ccd1cee9b2cb66b79a3d6bacde444/.travis.yml#L116-L125
Travis CI docs:
* https://docs.travis-ci.com/user/deployment/releases/
The wheels are only built for tags, and the workflow will change a bit so we'll need to update the main `RELEASING.md` checklist, this `README.md` and `update-pillow-tag.sh`.
When releasing, we add and push a tag. It builds as normal (and also skips the "latest" jobs, we don't need to build/deploy them). The wheels are uploaded to a [matching tag release here in this repo](https://github.com/python-pillow/pillow-wheels/releases). 
We can then download the wheels from the release, and …
=> Upload wheels to GitHub Releases

README.rst, update-pillow-tag.sh
Sequel to #156
As suggested there, updates README now that the wheel destination has changed, and changes update-pillow-tag.sh to tag the update commit and push the tag.
=> Updates for GitHub Releases

config.sh
Reverts https://github.com/python-pillow/pillow-wheels/pull/147/commits/639793e150a6c5f1968f32271660a7c8326ccb20 and instead fixes the problem with https://github.com/matthew-brett/multibuild/pull/342. The multibuild PR changes from 'cmake28' to 'cmake' as we were doing, and instead of our install of xz-devel, skips building xz.
=> Revert "Workaround problems with cmake and xz on manylinux2014"

config.sh
While [pillow-depends](https://github.com/python-pillow/pillow-depends) is used by this repo for the dependency archives, the test images from depends are not used. This PR fixes that.
This is worthwhile just for the sake of more testing, but it also fixes a problem with master - because the depends test images are not present, https://github.com/python-pillow/Pillow/pull/4929 is now causing failures - https://travis-ci.org/github/python-pillow/pillow-wheels/jobs/729255498
Also could be a chance to test mergify on this PR?
=> Use pillow-depends test images

config.sh
Currently, `build_openjpeg` is performed before `build_lcms2`.
In [multibuild, `build_openjpeg` runs `build_lcms2` though](https://github.com/matthew-brett/multibuild/blob/bc8e01eac30648347b0dc687d6ab38158e016c57/library_builders.sh#L197-L202).
So if `build_lcms2` were to fail, then it would appear to be part of our `build_openjpeg` step, and our `build_lcms2` is unlikely to ever fail.
This PR changes the order of steps to better help potential debugging.
=> Changed order of dependency

.travis.yml, config.sh
Helps https://github.com/python-pillow/Pillow/issues/4953
Adds Python 3.9 Travis jobs, as well as updating multibuild to include https://github.com/matthew-brett/multibuild/pull/359 and making use of https://github.com/python-pillow/pillow-depends/pull/33
=> Added Python 3.9

config.sh
Sequel to #164, now that xcb-proto 1.14.1 has been released.
=> Updated xcb-proto to 1.14.1

.github/workflows/build.sh, .github/workflows/wheels.yml, .travis.yml, config.sh
This PR moves the x86 and x86_64 builds to GHA (needs to be manually enabled it seems). Unlike Travis CI, which has 5 parallel jobs, and the .org version has been slow lately, GHA gives 20 parallel jobs (max 5 macOS).
The GHA build of 20 Ubuntu and 10 macOS jobs takes ~30m, barely slower than the remaining 8 Arm64 builds on Travis.org (~26m) if queued immediately. Note that Arm64 seems to have a separate queue and is less affected by the slowdown.
Also adds a Linux 32-bit PyPy wheel, as I do not see a reason it was not added in #153. 
The macOS build uses the default XCode, currently 12.0.1. https://github.com/actions/virtual-environments/issues/1712 shows how to pin to a specific version if necessary. XCode 10.3 is the oldest version currently available: …
=> Move x86 jobs to GHA

README.rst
Adds GitHub Actions badge after #169 added GitHub Actions
See https://github.com/radarhere/pillow-wheels/blob/badge/README.rst as a preview.
=> Added GitHub Actions badge

.github/workflows/build.sh
MacOS builds started failing because the Brew version of curl depends on zstd which is explicitly removed due to conflicts. Removing curl from Brew fixes this by using the system version of curl which does not need the brew zstd package.
=> GHA: Fix macOS builds

.github/workflows/build.sh, .github/workflows/wheels.yml
Add pypy3.7 wheels. At some point perhaps pillow should consider dropping python3.6 across all implementations.
=> Add PyPy3.7 wheels

config.sh
Updating multibuild to include https://github.com/matthew-brett/multibuild/pull/381, `IS_OSX` can now be replaced by `IS_MACOS` - which is a more suitable name, since 'OS X' hasn't been used by Apple since 10.11.
=> Move from multibuild IS_OSX to IS_MACOS

.github/workflows/build.sh, .github/workflows/wheels.yml, config.sh
Helps https://github.com/python-pillow/Pillow/issues/5093
Updating multibuild to include https://github.com/matthew-brett/multibuild/pull/383 and https://github.com/matthew-brett/multibuild/pull/384, this PR adds a job to build an arm64 wheel on x86_64 (https://github.com/actions/runner/issues/805 would indicate that running arm64 directly is not an option).
Some notes
- It only builds Python 3.9, as ['3.9.1 is the first version of Python to support macOS 11 Big Sur'](https://www.python.org/downloads/release/python-391/)
- It skips openjpeg and xcb due to errors.
- It doesn't test the wheel, since the arm64 wheel can't be installed on x86_64. However, I have downloaded the wheel and tested it on my M1 machine, and it works.
Most importantly though, …
=> Build arm64 wheel

config.sh
Workaround for failing pypy3.7 32-bit jobs, as seen in #186
=> Limit numpy to 1.19.5 on 32-bit pypy 3.7

.github/workflows/wheels.yml
https://github.com/python-pillow/pillow-wheels/runs/1849032310?check_suite_focus=true#step:4:5748 shows
> [PyPy 7.3.0 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
This PR updates it - https://github.com/python-pillow/pillow-wheels/pull/191/checks?check_run_id=1853722612#step:4:4970
> [PyPy 7.3.3 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
=> Updated PyPy 3.6 to 7.3.3

config.sh
If I try to [build openjpeg](https://github.com/radarhere/pillow-wheels/commit/dc891e7560a5b8f0be6379cb99b3f51da485faeb) on arm64, it fails. Part of the error is "[ld: warning: ignoring file /usr/local/lib/libpng.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64](https://github.com/radarhere/pillow-wheels/runs/1857866652?check_suite_focus=true#step:4:3172)".
If I remove the existing libpng (on other macOS architectures as well, because why not, we're building our own anyway), then the job runs correctly - https://github.com/radarhere/pillow-wheels/runs/1859658262
=> Removed existing libpng to fix arm64 OpenJPEG

config.sh, dependency_licenses/HARFBUZZ.txt, dependency_licenses/RAQM.txt
For https://github.com/python-pillow/Pillow/pull/5062.
~~See passing run in my branch: https://github.com/nulano/pillow-wheels/actions/runs/684862775~~
More comments inline below.
=> Update config for FriBiDi dynamic linking

.github/workflows/wheels.yml
> Ubuntu 16.04 is being deprecated. It is not recommended for new users.
> If any of your workflows use Ubuntu 16.04, migrate to Ubuntu 20.04 or 18.04.
https://github.com/actions/virtual-environments/issues/3287
=> Change workflow to use ubuntu-20.04

config.sh
xproto is an archived project - https://gitlab.freedesktop.org/xorg/proto/xproto
> Archived project! Repository and other project resources are read only
https://gitlab.freedesktop.org/xorg/proto/xproto/-/blob/0657164905c607e1b2b1dbac2707b06460a9e2f4/autogen.sh
> #!/bin/sh
>
> echo "This module has been deprecated. Use xorgproto instead:"
> echo "git clone git://anongit.freedesktop.org/git/xorg/proto/xorgproto"
>
> exit 1
This PR migrates to xorgproto instead, which fixes xcb on macOS 11.
=> Migrated from deprecated xproto to xorgproto

.github/workflows/wheels.yml, config.sh
Python 3.8.10 now supports M1 - https://www.python.org/downloads/release/python-3810/
> But there's a bunch of important updates here regardless, the biggest being Big Sur and Apple Silicon build support.
So this PR adds a Python 3.8 M1 build. It also updates multibuild to include https://github.com/matthew-brett/multibuild/pull/407, so that 3.8 is 3.8.10.
While I'm here, I'm including part of https://github.com/matthew-brett/multibuild/pull/406. It fixes multibuild's `untar` function on M1 (see https://github.com/radarhere/pillow-wheels/runs/2619227992 for a failure without this, and https://github.com/radarhere/pillow-wheels/runs/2620094931 for a pass with it).
=> Added Python 3.8 for arm64

.travis.yml
Also removes unused `MACOSX_DEPLOYMENT_TARGET` variable.
=> Updated Travis CI to Ubuntu 20.04

config.sh
https://github.com/python-pillow/Pillow/issues/5544 points out that our Linux wheels contain zlib 1.2.3.
Despite
https://github.com/python-pillow/pillow-wheels/blob/fd81da7e32593d38b69930b72a74178a4b1e74f9/config.sh#L10
We're only currently upgrading it on macOS.
https://github.com/python-pillow/pillow-wheels/blob/fd81da7e32593d38b69930b72a74178a4b1e74f9/config.sh#L48-L51
So this PR runs `build_new_zlib` on Linux as well.
There is a [warning attached to this in multibuild.](https://github.com/matthew-brett/multibuild/blob/7642786fb6085c459dc1fdd83a9ab41195f3f1e0/library_builders.sh#L146-L150), but that would only be a warning for our build process, not for the end user.
> Careful, this one may cause yum to segfault
See https://github.com/radarhere/pillow-wheels/commit/874bb0a48f3d2c14da6f8 …
=> Build zlib on Linux as well

.github/workflows/build.sh
Fixes the recent build failure, noted in https://github.com/python-pillow/pillow-wheels/pull/204#issuecomment-862631104
When `brew install openblas` is run before running tests, [brew reinstalls zstd](https://github.com/nulano/pillow-wheels/runs/2842802623?check_suite_focus=true#step:4:6661) (which was removed in `build.sh` due to compile errors IIRC). It then notices that the php package depends on zstd and [attempts to reinstall its dependencies](https://github.com/nulano/pillow-wheels/runs/2842802623?check_suite_focus=true#step:4:6682) (which were removed in `build.sh` due to conflicts). These [fail to install from brew](https://github.com/nulano/pillow-wheels/runs/2842802623?check_suite_focus=true#step:4:6708) because they were installed from source during Pillow compilation.
Removing …
=> OSX: brew remove php

config.sh
master is currently failing on 64-bit PyPy 3.7 - https://github.com/python-pillow/pillow-wheels/runs/2903167814
I find that fixing the numpy version to 1.20.3 resolves this.
=> Limit numpy on 64-bit pypy 3.7 as well

config.sh
Sequel to #208. This updates multibuild to include https://github.com/matthew-brett/multibuild/pull/413, allowing the second workaround to be removed.
=> Removed multibuild workaround

config.sh
Resolves https://github.com/python-pillow/Pillow/issues/5604
When #208 updated multibuild, part of the update switched to using [`brew install xz` on macOS instead of `build_xz`](https://github.com/matthew-brett/multibuild/pull/406/commits/d451c58f89b270d3c67130cae27939305468e637).
Two reasons why we should `build_xz` to compile it from source instead -
1. By compiling it from source, we respect our deployment target, whereas [Homebrew just targets the current OS version.](https://github.com/Homebrew/legacy-homebrew/issues/48437#issuecomment-174522431). This led to https://github.com/python-pillow/Pillow/issues/5604
2. We previously uninstalled Homebrew xz since it can ["cause a conflict with building webp and libtiff"](https://github.com/python-pillow/pillow-wheels/blob/90fdd92a9e26da0acb …
=> Added build_xz

.github/workflows/lint.yml, .pre-commit-config.yaml, .travis.yml
Helps https://github.com/python-pillow/Pillow/issues/5569.
Also:
* Replace EOL Xenial with Focal, because the Xenial images contain an older version of pip which doesn't support Python 3.10
* Add some simple YAML/merge conflict linting (it caught some YAML indent mistakes I made from commenting/uncommenting)
=> Travis CI: Build on Python 3.10-dev 

.github/workflows/build.sh
Suggested in https://github.com/python-pillow/pillow-wheels/pull/217#issuecomment-906182740, this PR updates the docker test image for Linux PyPy to focal... but only for 64-bit, since there aren't 32-bit focal images available at https://hub.docker.com/u/multibuild
https://github.com/multi-build/docker-images/pull/14 and https://github.com/multi-build/docker-images/pull/15 fixed the problem that I [originally](https://github.com/python-pillow/pillow-wheels/pull/217#issuecomment-906379167) had in making this update.
This also has a commit allowing `MB_PYTHON_OSX_VER` to be set on Linux and `DOCKER_TEST_IMAGE` to be set on macOS - since it simplifies the code and has no effect.
=> Test 64-bit Linux PyPy on focal

.travis.yml
For https://github.com/python-pillow/Pillow/issues/5711 / https://github.com/python-pillow/Pillow/issues/5711#issuecomment-919069172.
Re: https://twitter.com/peter_szilagyi/status/1437646118700175360.
The `travis` CLI tool is being difficult:
```console
$ travis login --auto --com
Successfully logged in as hugovk!
$ travis encrypt --com
repository not known to https://api.travis-ci.com/: python-pillow/pillow-wheels/
```
So I've put the regenerated GitHub personal access token as a private environment variable at:
https://app.travis-ci.com/github/python-pillow/pillow-wheels/settings
This also makes it easier and quicker to delete/rotate the key in future.
=> Update GitHub Releases API token

.travis.yml
The build from https://github.com/python-pillow/pillow-wheels/pull/221 errored with "Bad credentials":
```
/home/travis/.rvm/gems/ruby-2.7.0/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://docs.github.com/rest (Octokit::Unauthorized)
```
https://app.travis-ci.com/github/python-pillow/pillow-wheels/jobs/537440637#L7117
Looks like `secure:` is only needed for vars which are encrypted and pasted into the `.travis.yml`, for comparison:
* https://github.com/hellosign/hellosign-embedded/blob/0364b978c2e8357b2d4f5a0ba4d4c56b654455d4/.travis.yml#L80
* https://travis-ci.org/github/hellosign/hellosign-embedded/builds/771573691
=> Update GH Releases key

.gitmodules
Development has moved from https://github.com/matthew-brett/multibuild/ to https://github.com/multi-build/multibuild
=> Changed multibuild remote from matthew-brett to multi-build

.gitmodules
GitHub will be removing support for `git://`
* https://github.blog/2021-09-01-improving-git-protocol-security-github/
=> Update GitHub git:// to https://

config.sh
If I checkout main as main2, just to rerun it, it fails - https://github.com/python-pillow/pillow-wheels/actions/runs/1633179830
This PR
- expands #197 to cover more macOS jobs, since it seems GHA has upgraded others to macOS 11
- changes the NumPy versions. The latest version is now used for all jobs, except for 32-bit PyPy where 1.20.3 is used, and 32-bit Python 3.10, where 1.21.4 is used (presumably this is a result of the fact that [numpy doesn't seen a future for 32-bit wheels](https://github.com/python-pillow/pillow-wheels/pull/225#issuecomment-939269116)).
=> Fix failing main build

config.sh
Resolves https://github.com/python-pillow/Pillow/issues/5073
=> Switched to libjpeg-turbo

config.sh
If I checkout main as main2, just to rerun it, it fails - https://github.com/python-pillow/pillow-wheels/actions/runs/1645221714
This would be because numpy 1.22.0 was released yesterday.
=> Limit numpy on 32-bit to 1.21.5 for Python 3.8 and 3.9

.github/mergify.yml, .github/workflows/lint.yml, .github/workflows/wheels.yml
We've not updated Mergify in this repo after we added GitHub Actions, I was a little surprised when I added `automerge` to https://github.com/python-pillow/pillow-wheels/pull/240 and it merged after Travis CI passed but GHA was still running :)
=> Add GHA CI to Mergify

README.rst
https://travis-ci.com/github/python-pillow/pillow-wheels now redirects to https://app.travis-ci.com/github/python-pillow/pillow-wheels
=> Updated link

.travis.yml
Last bit for https://github.com/python-pillow/Pillow/issues/5569.
Three months after release, Travis CI finally has `3.10` available.
* https://travis-ci.community/t/add-python-3-10/12220/14?u=hugovk
=> Travis CI: Use Python 3.10

config.sh
This required a custom function as giflib >= 5.1.5 no longer has a 'configure' file.
I've created https://github.com/multi-build/multibuild/pull/449 to try and get this functionality merged upstream.
=> Updated giflib to 5.2.1 on Linux

.github/workflows/build.sh
Potential fix for https://github.com/python-pillow/Pillow/issues/6015
The generated wheel no longer contains dylibs with different permissions, but I don't have a mac system to test myself.
=> brew remove libxcb libxdmcp

README.rst
The README contains some instructions about NumPy.
> Check minimum NumPy versions to build against in .travis.yml file. Build against the earliest NumPy that Pillow is compatible with; see [forward, backward NumPy compatibility](https://stackoverflow.com/questions/17709641/valueerror-numpy-dtype-has-the-wrong-size-try-recompiling/18369312#18369312)
This was originally added in https://github.com/python-pillow/pillow-wheels/commit/2efbaa41d5507f0c9ad554
I don't think these special instructions are necessary, as we don't interact with NumPy at an ABI level. There are no special instructions for olefile, another optional Python dependency of Pillow. Also, .travis.yml doesn't currently mention NumPy at all.
So this PR suggests that we remove those instructions.
=> Removed NumPy instructions

.github/workflows/wheels.yml
Resolves warnings like https://github.com/python-pillow/pillow-wheels/runs/5228681289#step:4:6885
>   Tests/test_file_eps.py:292
>    /io/Pillow/Tests/test_file_eps.py:292: PytestUnknownMarkWarning: Unknown pytest.mark.timeout - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
>      @pytest.mark.timeout(timeout=5)
=> Added pytest-timeout

.github/workflows/wheels.yml, config.sh
Added PyPy 3.8. I'm avoiding PyPy 3.9 for now, as it is in "beta".
This PR also updates to 7.3.8.
=> Added PyPy3.8

.github/workflows/wheels-build.yml, .github/workflows/wheels.yml, .gitignore
We can refactor `build` and `build-latest` into a single _resuable workflow_ and pass inputs for their differences.
Docs:
* https://github.blog/2021-11-29-github-actions-reusable-workflows-is-generally-available/
* https://docs.github.com/en/actions/using-workflows/reusing-workflows
Not terribly happy with the `wheels.yml` + `wheels-reusable.yml` names, suggestions welcome!
---
Also put slower macOS first in the matrix, might speed things up a bit:
```diff
-        os: [ "ubuntu-20.04", "macos-latest" ]
+        os: [ "macos-latest", "ubuntu-20.04" ]
```
And while GHA gives 20 concurrent jobs, I just spotted the limit for macOS is 5: 
https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits
So another reason to get those queued up …
=> Remove duplication with a reusable workflow

.github/workflows/build.sh, .github/workflows/wheels-build.yml
For macOS arm64, rather than adding on Python 3.8-3.10, this PR removes Python 3.7 and PyPy.
I think this better communicates what is happening, but it's not exactly shorter, so feel free to disregard this if you want.
=> Refactored arm64 jobs to exclude rather than include

.github/workflows/build.sh, .github/workflows/wheels-linux.yml, .github/workflows/wheels-macos.yml, .github/workflows/wheels-ubuntu.yml, .github/workflows/wheels.yml, .gitmodules, config.sh
Resolves #226. Now that https://github.com/multi-build/multibuild/pull/430 has been merged, we are able to build musllinux wheels.
I'm still waiting on https://github.com/multi-build/multibuild/pull/465 though, so this PR temporarily diverges from the multibuild repository to my fork.
In order to accomodate macOS, manylinux and musllinux wheels, I have rearranged the jobs. Feel completely free to tell me you have a better idea for how to organise them.
As a note to self, it would be worth trying again with numpy after https://github.com/numpy/numpy/pull/21200 makes it into a release.
=> Added musllinux

config.sh
Add tests for https://github.com/python-pillow/Pillow/pull/6165
See passing in my repository until the above is merged: https://github.com/nulano/pillow-wheels/runs/5764443231?check_suite_focus=true#step:4:6501
=> Test with FriBiDi on Alpine

.github/workflows/wheels.yml
I've realised why the "Create release" job hasn't been running - I made a mistake in https://github.com/python-pillow/pillow-wheels/pull/271/commits/2471dbdd757708ab5d29eebc61e6a38198c2bcab
=> Corrected release runs-on

.gitmodules
Switches back to the main multibuild repository after #271.
Also updates multibuild to include https://github.com/multi-build/multibuild/pull/467, related to #276
=> Switched back to main multibuild repository

.github/workflows/build.sh
Resolves https://github.com/python-pillow/Pillow/issues/6179
If you look at the artifacts generated before https://github.com/python-pillow/pillow-wheels/pull/265, in https://github.com/python-pillow/pillow-wheels/actions/runs/2008816167 you see Pillow-9.0.1-cp38-cp38-macosx_10_10_x86_64.whl.
After that PR, in https://github.com/python-pillow/pillow-wheels/actions/runs/2011383640 you see Pillow-9.0.1-cp38-cp38-macosx_10_9_x86_64.whl.
So despite the fact that the PR was only intended to rearrange the jobs, there was a change. This is because in moving `MACOSX_DEPLOYMENT_TARGET`, I managed to break it. This is fixed here using `export`, and you can see that this PR generates Pillow-9.1.0-cp38-cp38-macosx_10_10_x86_64.whl again.
=> Fixed setting MACOSX_DEPLOYMENT_TARGET

config.sh
- Updated zlib on macOS to 1.2.12. Includes a workaround from https://github.com/madler/zlib/issues/615. Without the workaround, [an error occurs](https://github.com/radarhere/pillow-wheels/runs/5802112765) after zlib tries to build libz.so.1.2.12 instead of libz.1.2.12.dylib.
- Updated zlib on musllinux to 1.2.12. zlib was downgraded to 1.2.8 in #254, because of restrictions in [auditwheel's manylinux-policy.json](https://github.com/pypa/auditwheel/blob/main/src/auditwheel/policy/manylinux-policy.json), but there are no such restrictions in [musllinux-policy.json](https://github.com/pypa/auditwheel/blob/main/src/auditwheel/policy/musllinux-policy.json).
=> Updated zlib on macOS and musllinux to 1.2.12

config.sh
When #192 changed `EXP_CODECS`, it missed this possible simplification.
=> Simplified code

.github/workflows/build.sh, config.sh
https://github.com/multi-build/multibuild/pull/433 switched the default 64-bit manylinux test image to focal. This PR removes our custom setting for the test images, allowing that default to be used.
By itself, that change means that fribidi is no longer found when testing. I presumed that was due to a configuration difference between [matthew-brett/trusty](https://github.com/matthew-brett/trusty) and [multi-build/docker-images](https://github.com/multi-build/docker-images). It turns out that the official "ubuntu:14.04" image already has fribidi installed, but this is removed from 16.04 onwards. So instead, I install fribidi, finally meaning that pillow-wheels can test fribidi in all environments.
=> Test 64-bit manylinux on default focal

.github/workflows/build.sh, .travis.yml
This PR has a few commits cleaning up the Travis matrix
- `LATEST` is never set, so I've removed checks for it
- Travis `PLAT` is always "aarch64", so I've moved the configuration into the global section
- `DOCKER_TEST_IMAGE` is always "multibuild/focal_{PLAT}", so I've moved the configuration into the global section
And a few commits removing defaults
- `BUILD_DEPENDS` is [empty by default](https://github.com/multi-build/multibuild/blob/d0fdfdd42d1dfb82be1b7bddf185dd6a1c287bf8/common_utils.sh#L311), so this PR no longer specifies it as empty.
- `UNICODE_WIDTH` is [32 by default](https://github.com/multi-build/multibuild/blob/d0fdfdd42d1dfb82be1b7bddf185dd6a1c287bf8/common_utils.sh#L25), so this PR no longer specifies it as 32.
- `clean_code` uses `REPO_DIR` and `BUILD_COMMIT` as …
=> Cleanup code

config.sh
https://github.com/python-pillow/pillow-wheels/blob/68b95e37829260aee8312069332ca76ce7717a11/config.sh#L105
`$ORIGINAL_CFLAGS` is not defined. It was removed in #237, as I missed that it was still in use. This PR restores it.
=> Fixed restoring original CFLAGS

.github/workflows/build.sh, .travis.yml
Updates multibuild to include https://github.com/multi-build/multibuild/pull/468, allowing our `DOCKER_TEST_IMAGE="multibuild/focal_$PLAT"` settings to be removed.
=> multibuild now considers PLAT when selecting focal test images

.github/workflows/build.sh
macOS builds have started failing - https://github.com/python-pillow/pillow-wheels/actions/runs/2318590890
The arm64 build is failing while [building openjpeg](https://github.com/python-pillow/pillow-wheels/runs/6420505605?check_suite_focus=true#step:4:4545). `brew remove lcms2` fixes this.
The x86_64 build is failing while [reading XML as part of building the giflib docs](https://github.com/python-pillow/pillow-wheels/runs/6420505515?check_suite_focus=true#step:4:4711). If the XML tool, `xmlto`, is absent though, giflib doesn't try to build its docs, so `brew remove xmlto` fixes this.
[After that](https://github.com/radarhere/pillow-wheels/commit/60f497ffeac6c305f24a5964000707bda4e1ed1c), the build process completes, but [there is an error when the tests invoke …
=> brew remove lcms2 xmlto ghostscript

config.sh
Sequel to #293
After looking at https://github.com/uclouvain/openjpeg/pull/1410, I have customised `build_openjpeg` for macOS x86_64, to add in the `INSTALL_NAME_DIR`. This fixes the problem with the first commit in #293
=> Updated openjpeg to 2.5.0 on macOS x86_64

.github/workflows/wheels-linux.yml, .travis.yml, config.sh
Adds manylinux_2_28 wheels for x86_64 and aarch64 ([manylinux has not provided an image for i686](https://github.com/pypa/manylinux#manylinux_2_28-almalinux-8-based)).
This allows for zlib 1.2.12, rather than just 1.2.8.
We should keep the manylinux 2014 (a.k.a _2_17) wheels around as they provide support for [CentOS 7 and Amazon Linux 2.](https://github.com/python-pillow/pillow-wheels/pull/254#issue-1139500602)
=> Added manylinux_2_28

.github/workflows/build.sh, .github/workflows/wheels-linux.yml, .github/workflows/wheels-macos.yml, .travis.yml, config.sh
For https://github.com/python-pillow/Pillow/issues/6367
While I have created https://github.com/multi-build/multibuild/pull/477 and https://github.com/multi-build/docker-images/pull/35, they haven't been merged yet. While https://github.com/matthew-brett/trusty/pull/20 has been merged, [the 32-bit docker image hasn't been updated.](https://hub.docker.com/r/matthewbrett/trusty/tags)
So instead, this PR patches `fill_pyver` to cover the multibuild functionality, and switches to using my account for Python 3.11 docker test images.
=> Added Python 3.11.0b3

config.sh
Resolves https://github.com/python-pillow/pillow-wheels/issues/299
The issue reports that "ELF load command address/offset not page-aligned" may occur when using Pillow after it is stripped by pyinstaller.
I discovered point 3 of https://github.com/pypa/auditwheel/pull/376, and upgrading auditwheel to include that PR, the problem is resolved.
=> Updated auditwheel to include auditwheel#376

config.sh
https://github.com/python-pillow/Pillow/pull/6182 means that Pillow now checks /usr/local/lib/libfribidi.dylib.
So /usr/local/lib/libfribidi.dylib no longer needs to be symlinked to be found.
This will fail HEAD builds for now.
=> Removed symlink as Pillow now checks /usr/local/lib/libfribidi.dylib

README.rst
In the same line of thinking as https://github.com/python-pillow/Pillow/commit/48a65656eea5e18a031e992ce65553f338fae902
=> Use python3 when calling twine

config.sh
Updated multibuild to include https://github.com/multi-build/multibuild/pull/449. This means that the custom `build_giflib` function I added in #245 is now part of multibuild.
=> Updated multibuild to include build_giflib for giflib >= 5.1.5

config.sh
NumPy now supports Python 3.11 - https://github.com/numpy/numpy/releases/tag/v1.23.2
=> NumPy now supports Python 3.11

config.sh
#316 has found that the macOS Python 3.11 job is naming its wheels as universal2, rather than arm64 wheels like the other macOS jobs.
Part of #302 removed the `_PYTHON_HOST_PLATFORM` for Python 3.11. Looking back through my repository's builds, I apparently did this to avoid a delocate error.
That error no longer occurs, so this can be removed.
=> Restored _PYTHON_HOST_PLATFORM for Python 3.11

.github/workflows/build.sh
If #316 is interested in uploading new Python 3.11 wheels to PyPI, better to do it with the most recent version.
This PR overrides multibuild, which is [currently at b5](https://github.com/multi-build/multibuild/blob/85467f2c27ce82519ba763932e0d94d1b43edbf5/osx_utils.sh#L23). This can be seen in our current build - ["checking for python version... 3.11.0b5"](https://github.com/python-pillow/pillow-wheels/runs/8128516924?check_suite_focus=true#step:4:5458)
=> Updated Python 3.11 to rc1

config.sh, dependency_licenses/BROTLI.txt
Helps https://github.com/python-pillow/Pillow/issues/6554 by adding brotli.
After building brotli, delocate was unable to find the dependencies. I solved this by passing in `/usr/local/lib` through `DYLD_LIBRARY_PATH`, which allowed me to remove the custom `build_openjpeg` added in #294.
=> Added brotli

.github/workflows/build.sh
Python 3.11.0rc2 has been released - https://www.python.org/downloads/release/python-3110rc2/
=> Updated Python 3.11 to rc2

config.sh
Updated [libXau to 1.0.10](https://gitlab.freedesktop.org/xorg/lib/libxau/-/tags) and [xorgproto to 2022.2](https://github.com/freedesktop/xorg-xorgproto/releases/tag/xorgproto-2022.2)
=> Updated libXau and xorgproto

config.sh
Reverts the inclusion of a commit-specific version auditwheel from #298 now that [auditwheel 5.2.0](https://github.com/pypa/auditwheel/releases/tag/5.2.0) has been released
=> Updated auditwheel to 5.2.0

.github/workflows/lint.yml
Resolves warnings that occur at the moment.
https://github.com/python-pillow/pillow-wheels/actions/runs/3375616727/jobs/5602423188#step:3:7
> Warning: Neither 'python-version' nor 'python-version-file' inputs were supplied. Attempting to find '.python-version' file.
> Warning: .python-version doesn't exist.
> Warning: The `python-version` input is not set.  The version of Python currently in `PATH` will be used.
=> Specify Python version in Lint workflow

config.sh
Partially reverts https://github.com/python-pillow/pillow-wheels/pull/154/commits/505e915516def3757a6b627f6e8907a73a36cb0f, as a companion to https://github.com/python-pillow/Pillow/pull/6727 reverting https://github.com/python-pillow/Pillow/pull/4711
=> Do not install OpenBLAS on macOS for NumPy

.travis.yml
Resolves #346 by adding musllinux aarch64 wheels.
Temporarily specifies `DOCKER_TEST_IMAGE`, until https://github.com/multi-build/multibuild/pull/487 is merged.
=> Added musllinux aarch64

.github/workflows/wheels-linux.yml, .github/workflows/wheels-macos.yml, config.sh
PyPy 7.3.11 has been released - https://doc.pypy.org/en/latest/release-v7.3.11.html
https://foss.heptapod.net/pypy/pypy/-/issues/3868 was closed, so https://github.com/hugovk/pillow-wheels/pull/7 can be reverted, enabling tkinter on macOS PyPy again.
=> Updated PyPy to 7.3.11

README.rst
After https://github.com/python-pillow/Pillow/issues/6369, Pillow actually generates its own Windows wheels now.
A newcomer might expect those to be here, so this PR adds a note to explain where they are.
=> Link to Windows wheels

config.sh
Alternative to #357
Downgrade libXau to 1.0.10 on macOS 64-bit wheels to ensure compatibility with macOS < 11.
=> Downgraded libXau to 1.0.10 when targeting macOS 10.10

.github/workflows/build.sh, config.sh
Over in https://github.com/python-pillow/Pillow/issues/6862, it turns out that despite #358, users of Pillow 9.4.0 are still having issues on macOS < 11.
@nulano has looked at the [error message](https://github.com/python-pillow/Pillow/issues/6862#issue-1519878587),
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File ".venv/lib/python3.9/site-packages/PIL/Image.py", line 103, in <module>
from . import _imaging as core
ImportError: dlopen(.venv/lib/python3.9/site-packages/PIL/_imaging.cpython-39-darwin.so, 2): Library not loaded: @loader_path/libXdmcp.6.dylib
Referenced from: .venv/lib/python3.9/site-packages/PIL/.dylibs/libxcb.1.1.0.dylib
Reason: no suitable image found.  Did find:
.venv/lib/python3.9/site-packages/PIL/.dylibs/libXdmcp.6.dylib: cannot load …
```
=> Remove libxdmcp instead of downgrading libXau

.github/workflows/build.sh, config.sh
https://github.com/python-pillow/pillow-wheels/blob/2dac23efcd9c1cc42f18682c0996b3f1cb378ede/.github/workflows/build.sh#L8-L9
When attempting to `brew remove xmlto`, an error has started appearing - https://github.com/python-pillow/pillow-wheels/actions/runs/4011551998/jobs/6889238202#step:4:33
> Error: No such keg: /usr/local/Cellar/xmlto
It would seem that `xmlto` is no longer present by default. So this PR changes pillow-wheels to no longer attempt to remove it.
`xmlto` was originally removed in #292, to prevent an error when building giflib.
=> Do not attempt to remove xmlto

config.sh
freetype 2.13 has been released - https://sourceforge.net/projects/freetype/files/freetype2/2.13.0/
=> Updated freetype to 2.13

config.sh
In light of https://github.com/python-pillow/Pillow/pull/6918, switch to using the test-images repository, instead of copying images from pillow-depends.
=> Use test-images repository

.github/workflows/build.sh
macOS builds have started failing in main - https://github.com/python-pillow/pillow-wheels/actions/runs/4227780895/jobs/7342578793#step:4:1793
> configure: error: The pkg-config script could not be found or is too old.  Make sure it is in your PATH or set the PKG_CONFIG environment variable to the full path to pkg-config.
Adding `brew install pkg-config` fixes this.
=> brew install pkg-config

.github/workflows/wheels-linux.yml, .github/workflows/wheels-macos.yml
PyPy 7.3.12 has been released with Python 3.9 and 3.10 - https://www.pypy.org/posts/2023/06/pypy-v7312-release.html
=> Added PyPy 3.10 and removed PyPy 3.8

config.sh
Updates to use `--config-settings`, in light of https://github.com/python-pillow/Pillow/pull/7171. This provides fribidi, harfbuzz and raqm features on Python 3.12 for macOS.
This will cause the stable jobs to fail until Pillow 10 is released.
=> Use --config-settings

config.sh
Resolves https://github.com/python-pillow/Pillow/issues/7250
The issue found that using Pillow with py2app is currently failing with "ValueError: New Mach-O header is too large to relocate". I was able to reproduce this - https://github.com/radarhere/pillow-wheels/actions/runs/5492961738/jobs/10010803436#step:4:9563
I was able to fix this by adding the [standard](https://github.com/ronaldoussoren/py2app/issues/219#issuecomment-1305142378) fix to the libwebp flags - https://github.com/radarhere/pillow-wheels/actions/runs/5493088064
=> Fix py2app "New Mach-O header is too large" error

.travis.yml
Sequel to #398
https://github.com/multi-build/multibuild/pull/511 has now been merged, correcting a problem in passing the `REPO_DIR` environment variable around in multibuild.
So now, `build_multilinux` doesn't need the repository directory to be passed through by [`$build_cmds`](https://github.com/multi-build/multibuild/blob/509e63a6d8ab4705a500264d396b0e675798b6fc/travis_linux_steps.sh#L80-L86), and `$build_cmds` can just be "build_wheel" instead.
This means our copy of [`build_wheel`](https://github.com/multi-build/multibuild/blob/509e63a6d8ab4705a500264d396b0e675798b6fc/travis_linux_steps.sh#L28-L46) can just become `build_multilinux aarch64 build_wheel`
=> Use simpler build_multilinux command

config.sh
FreeType 2.13.2 has been released - https://freetype.org/
=> Updated freetype to 2.13.2

config.sh
- xorgproto-2023.2 is now available at https://www.x.org/archive/individual/proto
- libpthread-stubs-0.5 is now available at https://xcb.freedesktop.org/dist
- libxcb 1.16 has been released - https://gitlab.freedesktop.org/xorg/lib/libxcb/-/tags/libxcb-1.16. However, it is not available at https://xcb.freedesktop.org/dist/. I asked about this in https://gitlab.freedesktop.org/xorg/lib/libxcb/-/issues/71, and was told to use https://www.x.org/releases/individual/lib instead, as mentioned in the [announcement](https://lists.x.org/archives/xorg-announce/2023-August/003415.html)
- xcb-proto 1.16.0 has been released - https://gitlab.freedesktop.org/xorg/proto/xcbproto/-/tags/xcb-proto-1.16.0 - but is similarly not available at https://xcb.freedesktop.org/dist/. Instead, the …
=> Updated libxcb and dependencies

config.sh
https://github.com/python-pillow/pillow-wheels/actions/runs/6087453034/job/16516014212#step:4:7706
> SKIPPED [1] Tests/test_file_fpx.py:7: olefile not installed
https://github.com/python-pillow/pillow-wheels/actions/runs/6087453034/job/16516014212#step:4:7708
> SKIPPED [1] Tests/test_pyroma.py:5: Pyroma not installed
This PR installs those two libraries to improve testing, and also installs defusedxml, to better test the functionality started in https://github.com/python-pillow/Pillow/pull/5565
=> Install defusedxml, olefile and pyroma for tests

config.sh
zlib 1.3 has been released - https://zlib.net/
You will notice that the stable macOS jobs fail. This is because stable does not yet include https://github.com/python-pillow/Pillow/pull/7344. I half expect there to be a preference to delay merging this, to avoid almost 2 months of the wheels main failing until the next Pillow release updates stable.
You might wonder why the stable Linux jobs aren't failing. It is actually only reporting zlib 1.2.11. I have investigated, and can't find any evidence on the filesystem as to why this would be. In the absence of other options, I conclude it is related to https://github.com/pypa/auditwheel/blob/main/src/auditwheel/policy/manylinux-policy.json - in other words, I suspect this is the highest zlib version allowed for these manylinux wheels.
=> Updated zlib to 1.3

config.sh
With the release of NumPy 1.26.0, NumPy supports Python 3.12 - https://github.com/numpy/numpy/releases/tag/v1.26.0
This also fixes the failures that have [started happening on main](https://github.com/python-pillow/pillow-wheels/actions/runs/6217841175) due to [an absence of PyPy3.10 wheels for the NumPy release.](https://github.com/numpy/numpy/issues/24728)
=> NumPy now supports Python 3.12
